language: cpp
sudo: false
os: linux
dist: trusty
compiler: g++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6

srcipt: ./run_build.sh

#branches:
#  only:
#    - feature/travis
