language: cpp
sudo: false
os: linux
dist: trusty
compiler: gcc

env:
    matrix:
        - BUILD_NAME="debug-cthread"
        - BUILD_NAME="debug-tbb"       WITH_THREAD=tbb

cache:
    apt: true

#addons:
#   apt:
#       sources:
#           - ubuntu-toolchain-r-test
#       packages:
#           - g++-6

#script: source run_build.sh

script: source test.sh
