language: cpp
sudo: false
os: linux
dist: trusty
compiler: gcc
cache:
    apt: true

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-6

env:
    matrix:
        - BUILD_NAME="debug"
        - 
        #   the automatic checkout of tbb does not work
        #- BUILD_NAME="debug-tbb"       WITH_THREAD=tbb


before_script: source ./scripts/travis/defaults.sh
script: source ./scripts/travis/run_build.sh



