language: cpp
sudo: false
os: linux
dist: trusty
compiler: gcc
cache:
    apt: true

apt:
    sources:
        - ubuntu-toolchain-r-test

env:
    matrix:
        - BUILD_NAME="debug"
        - BUILD_NAME="debug-tbb"       WITH_THREAD=tbb
    apt:
        - packages:
            - g++-5
        - packages:
            - g++-6

before_script:
    - source ./scripts/travis/defaults.sh

script: source ./scripts/travis/run_build.sh

