language: cpp
sudo: false
os: linux
dist: trusty
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6

script: (source run_build.sh)

#branches:
#  only:
#    - feature/travis
