sudo: enabled
language: cpp
compiler: gcc
os: linux

addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-5

branches:
    only:
    - master


before_install:
- export CC=gcc-5
- export CXX=g++-5

srcipt: "source travis/run_build.sh"
