language: cpp
sudo: false
os: linux
dist: trusty
compiler: gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-6
            - openmpi-bin
            - libopenmpi-dev

env:
    # test single node/rank with threading backend
    - BUILD_NAME=cthread  WITH_DISTRIBUTED=serial
    # test mpi with threading backend
    - BUILD_NAME=mpi      WITH_DISTRIBUTED=mpi

before_install:
    - CC=gcc-6
    - CXX=g++-6

script: source ./scripts/travis/build.sh

