language: cpp
sudo: false
os: linux
dist: trusty
compiler: gcc
cache:
    apt: true

env:
    matrix:
        - BUILD_NAME="debug-cthread"
        - BUILD_NAME="debug-tbb"       WITH_THREAD=tbb


before_script: source ./scripts/travis/build_defaults.sh
script: source ./scripts/travis/test.sh

#addons:
#   apt:
#       sources:
#           - ubuntu-toolchain-r-test
#       packages:
#           - g++-6

#script: source ./scripts/travis/run_build.sh

