[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "scikit-build>=0.12",
]
build-backend = "setuptools.build_meta"

[[tool.cibuildwheel.overrides]]
select = "*-musllinux*"
before-all = "libxml2-dev" 
