name: Arbor on Wheels

on:
  push:
    branches: 
      - ciwheel
      - v*rc
    tags:
      - v*

  schedule:
    - cron: '0 2 * * 0' # run at 2 AM every sunday

jobs:
  build_binary_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Sitrep
        run: ls
      - name: Sitrep
        run: pwd
      - name: Create unique VERSION
        if: endsWith(github.ref,'ciwheel') || endsWith(github.ref,'rc') # https://docs.github.com/en/actions/learn-github-actions/expressions
        working-directory: GITHUB_WORKSPACE
        run: python3 -c 'import time;f=open("VERSION");content = f.readlines();print(content);print (content[0].strip()+time.strftime("%Y%m%d%H%I%S"))' > VERSION
      - name: Install cibuildwheel
        run: python3 -m pip install cibuildwheel
      - name: Build wheels
        run: python3 -m cibuildwheel --output-dir dist
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/*.whl

  build_sdist:
    name: Build sdist
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Get packages
        run: python3 -m pip install build
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Make sdist
        run: python3 -m build -s
      - name: Install sdist
        run:  python3 -m pip install dist/arbor*.tar.gz
      - name: Run Python tests
        run: python3 -m unittest discover -v -s python
      - name: Run Python examples
        run: scripts/run_python_examples.sh
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/*.tar.gz

  upload_test_pypi:
    name: upload to test pypi
    runs-on: ubuntu-latest
    needs: [build_binary_wheels, build_sdist]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
      - name: Sitrep
        run: ls
      - name: Publish distribution 📦 to Test PyPI
        run: |
          pip install twine
          twine upload -r testpypi ./*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TESTPYPI_SECRET }}
