name: Arbor on Wheels

on:
  push:
    branches: 
      - ciwheel
      - v*rc
    tags:
      - v*

  schedule:
    - cron: '0 2 * * 0' # run at 2 AM every sunday

jobs:
  build_binary_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Update pip
        run: python3 -m pip install --upgrade pip
        
      - name: Install cibuildwheel
        run: python3 -m pip install cibuildwheel

      - name: Build wheels
        run: python3 -m cibuildwheel --output-dir dist
      
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/*.whl

  build_sdist:
    name: Build sdist
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Update pip
        run: python3 -m pip install --upgrade pip
      - name: Get packages
        run: python3 -m pip install build #numpy setuptools scikit-build ninja cmake
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Make sdist
        run: python -m build -s
      - name: Install sdist
        run:  python3 -m pip install dist/arbor*.tar.gz
      - name: Run Python tests
        run: python3 -m unittest discover -v -s python
      - name: Run Python examples
        run: scripts/run_python_examples.sh
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/*.tar.gz

# TODO
  # upload_test_pypi:
  #   name: upload to test pypi
  #   runs-on: ubuntu-latest
  #   needs: [build_binary_wheels, build_sdist]
  #   steps:
  #     - uses: actions/download-artifact@v2
  #       with:
  #         name: dist
  #     - name: Publish distribution 📦 to Test PyPI
  #       run: |
  #         pip install twine
  #         twine upload -r testpypi dist/*
  #       env:
  #         TWINE_USERNAME: __token__
  #         TWINE_PASSWORD: ${{ secrets.ciwheeltest }}
