name: Ubuntu + GCC

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: "Generate docs"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:    ["ubuntu-20.04"]
        gcc:   [10"]
        py:    ["3.9"]
        cmake: ["3.18.x"]
        mpi:   ["OFF"]
    steps:
      - name: Set up cmake
        uses: jwlawson/actions-setup-cmake@v1.4
        with:
          cmake-version: ${{ matrix.cmake }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}
      - name: Check versions
        run: |
          python${{ matrix.py }} --version
          cmake --version
          gcc-${{ matrix.gcc }} --version
          g++-${{ matrix.gcc }} --version
      - name: "Clone w/ submodules"
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Install python packages
        run: python${{ matrix.py }} -mpip install sphinx sphinx-rtd-theme svgwrite
      - name: Install arbor
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_CXX_COMPILER=g++-${{ matrix.gcc }} -DCMAKE_C_COMPILER=gcc-${{ matrix.gcc }} -DARB_WITH_PYTHON=ON -DPYTHON_EXECUTABLE=`which python${{ matrix.py }}` -DARB_WITH_MPI=${{ matrix.mpi }}
          make html
