name: Mirroring

on: [push, delete]

jobs:
  to_gitlab:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url:
          https://ghpusher:${{ secrets.EBRAINS_GITLAB_SSH_PRIVATE_KEY }}@gitlab.ebrains.eu:arbor-sim/arbor.git
