name: Sanitize

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: "Lint"
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
      - name: Clone w/ submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Update pip
        run: |
          python -m pip install --upgrade pip
          pip install black
      - name: Lint python
        run: |
          black --check --extend-exclude '/(ext|python/pybind11|doc/scripts/.*_theme)' . scripts/build-catalogue.in
