name: Produce Arbor release artifacts

on:
  push:
    branches: 
      - ciwheel
    tags:
      - v*

  schedule:
    - cron: '0 2 * * 0' # run at 2 AM every sunday

jobs:
  get_timestamp:
    name: Prep VERSION
    runs-on: ubuntu-20.04

    steps:
      - name: Get Arbor
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Create unique VERSION
        if: startsWith(github.ref, 'refs/tags/v') == false
        run: python3 -c 'import time;f=open("VERSION","r+");content = f.readlines();f.seek(0);f.write(content[0].strip()+time.strftime("%Y%m%d%H%I%S"))'
      - uses: actions/upload-artifact@v3
        with:
            name: arbver
            path: ${{ github.workspace }}/VERSION

  build_binary_wheels:
    name: Build wheels on ${{ matrix.os }}
    needs: get_timestamp
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest]

    steps:
      - name: Get Arbor
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Delete VERSION
        run: rm -f VERSION
      - name: Get VERSION
        uses: actions/download-artifact@v3
        with:
          name: arbver
      - name: Check VERSION
        run: cat VERSION
      - name: Install cibuildwheel
        run: python3 -m pip install cibuildwheel
      - name: Build wheels
        run: python3 -m cibuildwheel --output-dir dist
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/*.whl

  build_sdist:
    name: Build sdist
    needs: get_timestamp
    runs-on: ubuntu-20.04

    steps:
      - name: Get packages
        run: python3 -m pip install build
      - name: Get Arbor
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Delete VERSION
        run: rm -f VERSION
      - name: Get VERSION
        uses: actions/download-artifact@v3
        with:
          name: arbver
      - name: Check VERSION
        run: cat VERSION
      - name: Make sdist
        run: python3 -m build -s
      - name: Install sdist
        run:  python3 -m pip install dist/arbor*.tar.gz
      - name: Run Python tests
        run: python3 -m unittest discover -v -s python
      - name: Run Python examples
        run: scripts/run_python_examples.sh
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/*.tar.gz

  upload_test_pypi:
    name: upload to test pypi
    runs-on: ubuntu-20.04
    needs: [build_binary_wheels, build_sdist]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
      - name: Publish distribution 📦 to Test PyPI
        run: |
          pip install twine
          twine upload -r testpypi ./*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TESTPYPI_SECRET }}

  make_release:
    name: draft new GitHub release
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-20.04
    needs: [build_binary_wheels, build_sdist]
    steps:
      - name: "Clone w/ submodules"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: "recursive"
          path: arbor
      - name: Make full tarball
        run: |
          the_ref=${{ github.ref }}
          the_tag="${the_ref/refs\/tags\//}"
          $GITHUB_WORKSPACE/arbor/scripts/create_tarball $GITHUB_WORKSPACE/arbor $the_tag $GITHUB_WORKSPACE/arbor-$the_tag-full.tar.gz
      - name: "Make Release"
        uses: ncipollo/release-action@v1
        with:
          omitBody: false
          draft: true
          prerelease: false
          generateReleaseNotes: true
          artifacts: '*.whl,*full.tar.gz'
          token: ${{ secrets.GITHUB_TOKEN }}
