name: Sanitize

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: "Sanitize"
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        name:      ["Sanitize"]
        sanitizer: ["address", "undefined", "memory", "thread"]
        simd:      ["ON", "OFF"]
    env:
        CC:           clang-10
        CXX:          clang++-10
        ASAN_OPTIONS: detect_leaks=1
    steps:
      - name: Set up cmake
        uses: jwlawson/actions-setup-cmake@v1.7
        with:
          cmake-version: 3.19.x
      - name: Clone w/ submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build arbor
        run: |
          mkdir build
          cd build
          echo 'src:/home/runner/work/arbor/arbor/ext/tinyopt/include/tinyopt/tinyopt.h' > /tmp/ignorelist.txt
          echo 'src:/home/runner/work/arbor/arbor/modcc/modcc.cpp' >> /tmp/ignorelist.txt
          echo ''
          cat /tmp/ignorelist.txt
          cmake .. -DCMAKE_BUILD_TYPE=debug -DCMAKE_CXX_FLAGS="-fsanitize=${{ matrix.sanitizer }} -fsanitize-blacklist=/tmp/ignorelist.txt -fno-omit-frame-pointer" -DCMAKE_C_FLAGS="-fsanitize=${{ matrix.sanitizer }} -fsanitize-blacklist=/tmp/ignorelist.txt -fno-omit-frame-pointer" -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=${{ matrix.sanitizer }} -fsanitize-blacklist=/tmp/ignorelist.txt" -DCMAKE_MODULE_LINKER_FLAGS="-fsanitize=${{ matrix.sanitizer }} -fsanitize-blacklist=/tmp/ignorelist.txt" -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_C_COMPILER=$CC -DARB_VECTORIZE=${{ matrix.simd }} -DARB_WITH_MPI=OFF -DARB_USE_BUNDLED_LIBS=ON
          make -j4 VERBOSE=1 tests examples
          cd -
      - name: Run unit tests
        run: |
          build/bin/unit --gtest_filter=-*DeathTest
          build/bin/unit-modcc
      - name: Run examples
        run: |
            build/bin/bench
            build/bin/brunel
            build/bin/dryrun
            build/bin/gap_junctions
            build/bin/generators
            build/bin/lfp
            build/bin/probe-demo v
            build/bin/ring
            build/bin/single-cell
