name: Spack

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        python-version: [3.8]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            path: arbor
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Spack cache
        uses: actions/cache@v3
        with:
          path: ~/.spack-cache
          key: spack-cache-${{ matrix.os }}-${{ github.run_id }}
          restore-keys: spack-cache-${{ matrix.os }}-

      - name: Build Arbor's Spack package against the latest release
        id: setup_spack
        run: arbor/scripts/build_spack_package.sh arbor latest_release

      - name: Run Python examples
        run: |
          source ${{ steps.setup_spack.outputs.SOURCE_SPACK }}"
          spack load arbor
          cd arbor
          scripts/run_python_examples.sh
      - name: Test executables
        run: |
          source ${{ steps.setup_spack.outputs.SOURCE_SPACK }}"
          spack load arbor
          cd arbor
          scripts/test_executables.sh
