name: Typestub

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Typestub
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Get packages
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Clone w/ submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install self
        run: pip install .
      - name: Check typestub
        run: ./ci/check_stub.py
