name: Update submodules

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  update_submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Clone w/ submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Check submodules for updates
        run: scripts/submodule-diff.sh
      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: [AUTOMATED] Git submodule updates found
          content-filepath: ./diff.log
          labels: |
            dependency update
          assignees: brenthuisman
